<?php
$modversion['name'] = _MYFRIENDS;
$modversion['version'] = "2.0";
$modversion['description'] = _MYFRIENDS_DESC;
$modversion['official'] = no;
$modversion['author'] = "Original version by<br/>p4@directfriends.com";
$modversion['credits'] = "Xoops module version by<br/>P4<br/> http://www.directfriends.com";
$modversion['admin'] = 0;
$modversion['dirname'] = "directfriends";
$modversion['image'] = "myfriends_logo.gif";
$modversion['license'] = "GPL see LICENSE";
$modversion['namemod'] = "directfriends";

// Blocks
$modversion['blocks'][1]['file'] = "myfriends.php";
$modversion['blocks'][1]['name'] = "Direct Friends";
$modversion['blocks'][1]['description'] = "A list of friends with fast PM";
$modversion['blocks'][1]['show_func'] = "myfriends_show";

// Menu
$modversion['hasMain'] = 1;

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "doc/myfriends.sql";
// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "myfriends";

?>
